package require -exact qsys 18.0
set qsys_system pcie_ed.qsys
set_project_property DEVICE_FAMILY "Agilex 5"
set_project_property DEVICE A5ED065BB32AE4SR0
# Adding GTS PCI Express Intel FPGA IP
add_component dut ip/pcie_ed/pcie_ed_dut.ip intel_pcie_gts dut
load_component dut
# Setting Parameters to GTS PCI Express Intel FPGA IP
set_component_parameter_value generating_ed_hwtcl 1
set_component_parameter_value pcie_ss_func_mode_hwtcl {Power User}
set_component_parameter_value pcie_ss_profile_hwtcl {Basic}
set_component_parameter_value axi_lite_clk_freq_user_hwtcl {250}
set_component_parameter_value axi_st_clk_freq_user_hwtcl {300MHz}
set_component_parameter_value DefaultMemory {0}
set_component_parameter_value pciess_perfmon_en_hwtcl {0}
set_component_parameter_value pciess_bp_debug_en_hwtcl {0}
set_component_parameter_value mif_devatt_port0_lower32b {}
set_component_parameter_value mif_devatt_port0_upper32b {}
set_component_parameter_value core16_ctrl_shadow_en_hwtcl {0}
set_component_parameter_value core16_comp_timeout_en_hwtcl {0}
set_component_parameter_value core16_ceb_en_hwtcl {0}
set_component_parameter_value core16_cii_en_hwtcl {0}
set_component_parameter_value core16_virtio_pci_cfg_acc_intf_en_hwtcl {0}
set_component_parameter_value core16_ptm_intf_en_hwtcl {0}
set_component_parameter_value core16_device_att_en_hwtcl {0}
set_component_parameter_value core16_cpl_timeout_thru_axist_en_hwtcl {0}
set_component_parameter_value core16_cpl_reordering_en_hwtcl {0}
set_component_parameter_value core16_reorder_buff_size_hwtcl {64}
set_component_parameter_value core16_msi_msg_gen_en_hwtcl {0}
set_component_parameter_value core16_msix_en_table_hwtcl {0}
set_component_parameter_value core16_dfl_en_hwtcl {0}
set_component_parameter_value core16_dfh_fid_hwtcl {0}
set_component_parameter_value core16_dfh_major_ver_hwtcl {0}
set_component_parameter_value core16_dfh_next_byte_offset_hwtcl {0}
set_component_parameter_value core16_dfh_end_hwtcl {0}
set_component_parameter_value core16_dfh_minor_rev_hwtcl {0}
set_component_parameter_value core16_dfh_ver_hwtcl {0}
set_component_parameter_value core16_dfh_feature_type_hwtcl {0}
set_component_parameter_value core16_inst_id_hwtcl {0}
set_component_parameter_value core16_Header_Packing_scheme_hwtcl {Simple}
set_component_parameter_value core16_segment_size_hwtcl {16}
set_component_parameter_value core16_LiteSlvDWD_byte_hwtcl {4}
set_component_parameter_value top_topology_hwtcl {Gen4 x4 Interface 256 bit}
set_component_parameter_value virtual_rp_ep_mode_hwtcl {Native Endpoint}
set_component_parameter_value debug_toolkit_hwtcl {0}
set_component_parameter_value g4_pld_clkfreq_user_hwtcl {350MHz}
set_component_parameter_value virtual_sris_enable_en_hwtcl {0}
set_component_parameter_value enable_example_design_sim_hwtcl {1}
set_component_parameter_value enable_example_design_synth_hwtcl {1}
set_component_parameter_value select_design_example_rtl_lang_hwtcl {Verilog}
set_component_parameter_value example_design_mode_hwtcl {PIO}
set_component_parameter_value core16_enable_rx_buffer_limit_ports_hwtcl {0}
set_component_parameter_value core16_virtual_maxpayload_size_hwtcl {512}
set_component_parameter_value core16_enable_legacy_int_hwtcl {0}
set_component_parameter_value core16_pf0_bar0_type_user_hwtcl {64-bit prefetchable memory}
set_component_parameter_value core16_pf0_bar0_address_width_user_hwtcl {16}
set_component_parameter_value core16_pf0_bar1_type_user_hwtcl {Disabled}
set_component_parameter_value core16_pf0_bar2_type_user_hwtcl {Disabled}
set_component_parameter_value core16_pf0_bar3_type_user_hwtcl {Disabled}
set_component_parameter_value core16_pf0_bar4_type_user_hwtcl {Disabled}
set_component_parameter_value core16_pf0_bar5_type_user_hwtcl {Disabled}
set_component_parameter_value core16_enable_multi_func_hwtcl {0}
set_component_parameter_value core16_enable_sriov_hwtcl {0}
set_component_parameter_value core16_cap_port_num_hwtcl {1}
set_component_parameter_value core16_cap_slot_clk_config_hwtcl {1}
set_component_parameter_value core16_virtual_pf0_msi_enable_user_hwtcl {1}
set_component_parameter_value core16_pf0_pci_msi_ext_data_cap_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msi_multiple_msg_cap_hwtcl {1}
set_component_parameter_value core16_virtual_pf0_msix_enable_user_hwtcl {0}
set_component_parameter_value core16_virtual_pf1_msix_enable_user_hwtcl {0}
set_component_parameter_value core16_virtual_pf2_msix_enable_user_hwtcl {0}
set_component_parameter_value core16_virtual_pf3_msix_enable_user_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msix_table_size_hwtcl {0}
set_component_parameter_value core16_pf1_pci_msix_table_size_hwtcl {0}
set_component_parameter_value core16_pf2_pci_msix_table_size_hwtcl {0}
set_component_parameter_value core16_pf3_pci_msix_table_size_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msix_table_offset_hwtcl {0}
set_component_parameter_value core16_pf1_pci_msix_table_offset_hwtcl {0}
set_component_parameter_value core16_pf2_pci_msix_table_offset_hwtcl {0}
set_component_parameter_value core16_pf3_pci_msix_table_offset_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msix_bir_hwtcl {0}
set_component_parameter_value core16_pf1_pci_msix_bir_hwtcl {0}
set_component_parameter_value core16_pf2_pci_msix_bir_hwtcl {0}
set_component_parameter_value core16_pf3_pci_msix_bir_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msix_pba_hwtcl {0}
set_component_parameter_value core16_pf1_pci_msix_pba_hwtcl {0}
set_component_parameter_value core16_pf2_pci_msix_pba_hwtcl {0}
set_component_parameter_value core16_pf3_pci_msix_pba_hwtcl {0}
set_component_parameter_value core16_pf0_pci_msix_pba_offset_hwtcl {0}
set_component_parameter_value core16_pf1_pci_msix_pba_offset_hwtcl {0}
set_component_parameter_value core16_pf2_pci_msix_pba_offset_hwtcl {0}
set_component_parameter_value core16_pf3_pci_msix_pba_offset_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_exvf_msix_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf1_exvf_msix_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf2_exvf_msix_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf3_exvf_msix_cap_enable_hwtcl {0}
set_component_parameter_value core16_exvf_msix_tablesize_pf0 {0}
set_component_parameter_value core16_exvf_msix_tablesize_pf1 {0}
set_component_parameter_value core16_exvf_msix_tablesize_pf2 {0}
set_component_parameter_value core16_exvf_msix_tablesize_pf3 {0}
set_component_parameter_value core16_exvf_msixtable_offset_pf0 {0}
set_component_parameter_value core16_exvf_msixtable_offset_pf1 {0}
set_component_parameter_value core16_exvf_msixtable_offset_pf2 {0}
set_component_parameter_value core16_exvf_msixtable_offset_pf3 {0}
set_component_parameter_value core16_exvf_msixtable_bir_pf0 {0}
set_component_parameter_value core16_exvf_msixtable_bir_pf1 {0}
set_component_parameter_value core16_exvf_msixtable_bir_pf2 {0}
set_component_parameter_value core16_exvf_msixtable_bir_pf3 {0}
set_component_parameter_value core16_exvf_msixpba_offset_pf0 {0}
set_component_parameter_value core16_exvf_msixpba_offset_pf1 {0}
set_component_parameter_value core16_exvf_msixpba_offset_pf2 {0}
set_component_parameter_value core16_exvf_msixpba_offset_pf3 {0}
set_component_parameter_value core16_exvf_msixpba_bir_pf0 {0}
set_component_parameter_value core16_exvf_msixpba_bir_pf1 {0}
set_component_parameter_value core16_exvf_msixpba_bir_pf2 {0}
set_component_parameter_value core16_exvf_msixpba_bir_pf3 {0}
set_component_parameter_value core16_pf0_pcie_slot_imp_hwtcl {0}
set_component_parameter_value core16_pf0_pcie_cap_slot_power_limit_scale_hwtcl {0}
set_component_parameter_value core16_pf0_pcie_cap_slot_power_limit_value_hwtcl {0}
set_component_parameter_value core16_pf0_pcie_cap_phy_slot_num_hwtcl {0}
set_component_parameter_value core16_user_pcie_cap_ep_l0s_accpt_latency_hwtcl {0}
set_component_parameter_value core16_user_pcie_cap_ep_l1_accpt_latency_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_prs_ext_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf1_prs_ext_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf2_prs_ext_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf3_prs_ext_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_sn_cap_enable_hwtcl {0}
set_component_parameter_value core16_sn_ser_num_reg_1_dw_hwtcl {0}
set_component_parameter_value core16_sn_ser_num_reg_2_dw_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_pasid_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf1_pasid_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf2_pasid_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf3_pasid_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_ltr_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_ptm_hwtcl {0}
set_component_parameter_value core16_cfg_ptm_auto_update_period_hwtcl {Disable}
set_component_parameter_value core16_pf0_pci_type0_vendor_id_hwtcl {4466}
set_component_parameter_value core16_pf0_pci_type0_device_id_hwtcl {0}
set_component_parameter_value core16_pf0_revision_id_hwtcl {1}
set_component_parameter_value core16_pf0_class_code_hwtcl {16711680}
set_component_parameter_value core16_pf0_subsys_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf0_subsys_dev_id_hwtcl {0}
set_component_parameter_value core16_pf0_sriov_vf_device_id {0}
set_component_parameter_value core16_pf1_pci_type0_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf1_pci_type0_device_id_hwtcl {0}
set_component_parameter_value core16_pf1_revision_id_hwtcl {0}
set_component_parameter_value core16_pf1_class_code_hwtcl {16711680}
set_component_parameter_value core16_pf1_subsys_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf1_subsys_dev_id_hwtcl {0}
set_component_parameter_value core16_pf1_sriov_vf_device_id {0}
set_component_parameter_value core16_pf2_pci_type0_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf2_pci_type0_device_id_hwtcl {0}
set_component_parameter_value core16_pf2_revision_id_hwtcl {0}
set_component_parameter_value core16_pf2_class_code_hwtcl {16711680}
set_component_parameter_value core16_pf2_subsys_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf2_subsys_dev_id_hwtcl {0}
set_component_parameter_value core16_pf2_sriov_vf_device_id {0}
set_component_parameter_value core16_pf3_pci_type0_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf3_pci_type0_device_id_hwtcl {0}
set_component_parameter_value core16_pf3_revision_id_hwtcl {0}
set_component_parameter_value core16_pf3_class_code_hwtcl {16711680}
set_component_parameter_value core16_pf3_subsys_vendor_id_hwtcl {0}
set_component_parameter_value core16_pf3_subsys_dev_id_hwtcl {0}
set_component_parameter_value core16_pf3_sriov_vf_device_id {0}
set_component_parameter_value core16_cvp_user_id_hwtcl {0}
set_component_parameter_value core16_virtual_drop_vendor0_msg_hwtcl {0}
set_component_parameter_value core16_virtual_drop_vendor1_msg_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_ats_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_tph_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_pf0_acs_cap_enable_hwtcl {0}
set_component_parameter_value core16_virtual_num_of_lanes_4_hwtcl {4}
set_component_parameter_value core16_pf0_int_pin_hwtcl {NO INT}
set_component_parameter_value core16_pf0_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf0vf_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf1vf_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf2vf_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_capability_present_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_device_specific_cap_present_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_cmn_config_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_cmn_config_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_cmn_config_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_notification_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_notification_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_notification_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_notify_off_multiplier_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_isrstatus_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_isrstatus_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_isrstatus_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_devspecific_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_devspecific_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_devspecific_structure_length_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_pciconfig_access_bar_indicator_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_pciconfig_access_bar_offset_hwtcl {0}
set_component_parameter_value core16_pf3vf_virtio_pciconfig_access_structure_length_hwtcl {0}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch0_rx_invert_pin_hwtcl {ENABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch1_rx_invert_pin_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch2_rx_invert_pin_hwtcl {ENABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch3_rx_invert_pin_hwtcl {ENABLE}
set_component_parameter_value dr_enabled_hwtcl {DR_DISABLED}
set_component_parameter_value ch0_flux_mode_hwtcl {FLUX_MODE_BYPASS}
set_component_parameter_value ch1_flux_mode_hwtcl {FLUX_MODE_BYPASS}
set_component_parameter_value ch2_flux_mode_hwtcl {FLUX_MODE_BYPASS}
set_component_parameter_value ch3_flux_mode_hwtcl {FLUX_MODE_BYPASS}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch0_xcvr_rx_cdrdivout_en_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch1_xcvr_rx_cdrdivout_en_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch2_xcvr_rx_cdrdivout_en_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch3_xcvr_rx_cdrdivout_en_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch0_rx_postdiv_clk_en_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch1_rx_postdiv_clk_en_hwtcl {ENABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch2_rx_postdiv_clk_en_hwtcl {ENABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch3_rx_postdiv_clk_en_hwtcl {ENABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch0_xcvr_tx_user_clk_only_mode_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch1_xcvr_tx_user_clk_only_mode_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch2_xcvr_tx_user_clk_only_mode_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch3_xcvr_tx_user_clk_only_mode_hwtcl {DISABLE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch0_xcvr_rx_force_cdr_ltr_hwtcl {TRUE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch1_xcvr_rx_force_cdr_ltr_hwtcl {TRUE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch2_xcvr_rx_force_cdr_ltr_hwtcl {FALSE}
set_component_parameter_value ipfluxtop_uxtop_wrap_ch3_xcvr_rx_force_cdr_ltr_hwtcl {FALSE}
set_component_parameter_value ch0_tx_pll_f_out_hz_hwtcl {0}
set_component_parameter_value ch1_tx_pll_f_out_hz_hwtcl {0}
set_component_parameter_value ch2_tx_pll_f_out_hz_hwtcl {0}
set_component_parameter_value ch3_tx_pll_f_out_hz_hwtcl {0}
set_component_parameter_value ch0_cdr_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch1_cdr_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch2_cdr_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch3_cdr_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch0_phy_loopback_mode_hwtcl {DISABLED}
set_component_parameter_value ch1_phy_loopback_mode_hwtcl {DISABLED}
set_component_parameter_value ch2_phy_loopback_mode_hwtcl {DISABLED}
set_component_parameter_value ch3_phy_loopback_mode_hwtcl {DISABLED}
set_component_parameter_value ch0_xcvr_tx_spread_spectrum_en_hwtcl {ENABLE}
set_component_parameter_value ch1_xcvr_tx_spread_spectrum_en_hwtcl {ENABLE}
set_component_parameter_value ch2_xcvr_tx_spread_spectrum_en_hwtcl {ENABLE}
set_component_parameter_value ch3_xcvr_tx_spread_spectrum_en_hwtcl {ENABLE}
set_component_parameter_value ch0_xcvr_cdr_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch1_xcvr_cdr_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch2_xcvr_cdr_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch3_xcvr_cdr_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch0_tx_pll_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch1_tx_pll_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch2_tx_pll_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch3_tx_pll_f_ref_hz_hwtcl {100000000}
set_component_parameter_value ch0_xcvr_cdr_f_vco_hz_hwtcl {1410065408}
set_component_parameter_value ch1_xcvr_cdr_f_vco_hz_hwtcl {1410065408}
set_component_parameter_value ch2_xcvr_cdr_f_vco_hz_hwtcl {1410065408}
set_component_parameter_value ch3_xcvr_cdr_f_vco_hz_hwtcl {1410065408}
set_component_parameter_value ch0_rx_postdiv_clk_divider_hwtcl {12}
set_component_parameter_value ch1_rx_postdiv_clk_divider_hwtcl {12}
set_component_parameter_value ch2_rx_postdiv_clk_divider_hwtcl {12}
set_component_parameter_value ch3_rx_postdiv_clk_divider_hwtcl {12}
set_component_parameter_value ch0_tx_postdiv_clk_divider_hwtcl {52}
set_component_parameter_value ch1_tx_postdiv_clk_divider_hwtcl {137}
set_component_parameter_value ch2_tx_postdiv_clk_divider_hwtcl {73}
set_component_parameter_value ch3_tx_postdiv_clk_divider_hwtcl {4}
set_component_parameter_value ch0_xcvr_tx_prbs_pattern_hwtcl {DISABLE}
set_component_parameter_value ch1_xcvr_tx_prbs_pattern_hwtcl {DISABLE}
set_component_parameter_value ch2_xcvr_tx_prbs_pattern_hwtcl {DISABLE}
set_component_parameter_value ch3_xcvr_tx_prbs_pattern_hwtcl {DISABLE}
set_component_parameter_value ch0_xcvr_rx_adaptation_mode_hwtcl {UX_NATIVE_ADAPTATION}
set_component_parameter_value ch1_xcvr_rx_adaptation_mode_hwtcl {UX_NATIVE_ADAPTATION}
set_component_parameter_value ch2_xcvr_rx_adaptation_mode_hwtcl {UX_NATIVE_ADAPTATION}
set_component_parameter_value ch3_xcvr_rx_adaptation_mode_hwtcl {UX_NATIVE_ADAPTATION}
set_component_parameter_value ch0_xcvr_rx_width_hwtcl {16}
set_component_parameter_value ch1_xcvr_rx_width_hwtcl {16}
set_component_parameter_value ch2_xcvr_rx_width_hwtcl {16}
set_component_parameter_value ch3_xcvr_rx_width_hwtcl {16}
set_component_parameter_value ch0_tx_pll_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch1_tx_pll_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch2_tx_pll_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch3_tx_pll_refclk_select_hwtcl {GLOBAL_REFCLK0}
set_component_parameter_value ch0_tx_invert_pin_hwtcl {DISABLE}
set_component_parameter_value ch1_tx_invert_pin_hwtcl {DISABLE}
set_component_parameter_value ch2_tx_invert_pin_hwtcl {ENABLE}
set_component_parameter_value ch3_tx_invert_pin_hwtcl {DISABLE}
set_component_parameter_value ch0_sim_mode_hwtcl {DISABLE}
set_component_parameter_value ch1_sim_mode_hwtcl {DISABLE}
set_component_parameter_value ch2_sim_mode_hwtcl {DISABLE}
set_component_parameter_value ch3_sim_mode_hwtcl {DISABLE}
save_component
load_instantiation dut
add_instantiation_interface             hip_serial conduit INPUT
set_instantiation_interface_parameter_value hip_serial associatedClock {}
set_instantiation_interface_parameter_value hip_serial associatedReset {}
set_instantiation_interface_parameter_value hip_serial prSafe {false}
add_instantiation_interface_port hip_serial rx_n_in0 rx_n_in0 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_n_in1 rx_n_in1 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_n_in2 rx_n_in2 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_n_in3 rx_n_in3 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_p_in0 rx_p_in0 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_p_in1 rx_p_in1 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_p_in2 rx_p_in2 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial rx_p_in3 rx_p_in3 1 STD_LOGIC Input
add_instantiation_interface_port hip_serial tx_n_out0 tx_p_out0 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_n_out1 tx_p_out1 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_n_out2 tx_p_out2 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_n_out3 tx_p_out3 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_p_out0 tx_p_out0 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_p_out1 tx_p_out1 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_p_out2 tx_p_out2 1 STD_LOGIC Output
add_instantiation_interface_port hip_serial tx_p_out3 tx_p_out3 1 STD_LOGIC Output
set_interface_property    hip_serial EXPORT_OF dut.hip_serial
set_interface_property    pin_perst_n EXPORT_OF dut.pin_perst_n
set_interface_property    i_gpio_perst0_n EXPORT_OF dut.i_gpio_perst0_n
save_instantiation

# Adding Reset Release IP
add_component resetIP ip/pcie_ed/pcie_ed_resetIP.ip altera_s10_user_rst_clkgate resetIP
load_component resetIP
set_component_parameter_value outputType       {Reset Interface}
save_component
add_connection resetIP.ninit_done dut.ninit_done

set syspll_in_refclk_intf             refclk_xcvr
set syspll_out_syspll_c0_intf         o_syspll_c0
set syspll_out_syspll_c1_intf         o_syspll_c1
set syspll_out_syspll_c2_intf         o_syspll_c2
set syspll_out_pll_lock_intf          o_pll_lock

set pcie_in_refclk0_intf              refclk0
set pcie_in_syspll_c0_clk_intf        i_syspll_c0_clk
set pcie_in_pll_lock_intf             i_ss_vccl_syspll_locked

load_instantiation dut
add_instantiation_interface             refclk0 clock INPUT
add_instantiation_interface_port refclk0 refclk0 clk 1 STD_LOGIC Input
set_interface_property    refclk0 EXPORT_OF dut.refclk0
add_instantiation_interface i_flux_clk_wirelevel wirelevel INPUT
set_instantiation_interface_parameter_value i_flux_clk_wirelevel originalType {conduit}
add_instantiation_interface_port i_flux_clk_wirelevel i_flux_clk clk 1 STD_LOGIC Input
save_instantiation

# Adding System PLL
add_component syspll_inst ip/pcie_ed/pcie_ed_syspll.ip intel_systemclk_gts
load_component syspll_inst
set_component_parameter_value  syspll_use_case        "TRANSCEIVER_USE_CASE"
set_component_parameter_value  syspll_mod_0           "PCIE_FREQ_350"
set_component_parameter_value  syspll_freq_mhz_enable_0      1
set_component_parameter_value  syspll_freq_mhz_0      350.000000
set_component_parameter_value  syspll_freq_mhz_enable_1      1
set_component_parameter_value  syspll_freq_mhz_1      350.000000
set_component_parameter_value  syspll_freq_mhz_enable_2      1
set_component_parameter_value  syspll_freq_mhz_2      350.000000
set_component_parameter_value  refclk_xcvr_freq_mhz_0 100.000000
save_component

# get instance interface
set syspll_all_intf             [get_instance_interfaces syspll_inst]

# add the interface & exports
foreach intf $syspll_all_intf {
   if {$intf == "$syspll_in_refclk_intf"} {
      set_interface_property $intf EXPORT_OF syspll_inst.$intf
   }
}

# add wirelevel expressions
set_wirelevel_expression {dut.i_flux_clk} {srcssIP.o_pma_cu_clk[0]}

# add the connections
add_connection syspll_inst.${syspll_out_syspll_c0_intf}/dut.$pcie_in_syspll_c0_clk_intf
add_connection syspll_inst.${syspll_out_pll_lock_intf}/dut.$pcie_in_pll_lock_intf

# Adding SRCSS
add_component                 srcssIP ip/pcie_ed/pcie_ed_srcssIP.ip intel_srcss_gts srcssIP
load_component                srcssIP
set_component_parameter_value NUM_LANES_SHORELINE 1
set_component_parameter_value NUM_BANKS_SHORELINE 1
set_component_parameter_value SRC_RS_DISABLE  1
save_component

# Adding PIO
add_component pio0 ip/pcie_ed/pcie_ed_pio0.ip intel_pcie_pio_gts pio0
load_component pio0
set_component_parameter_value DATA_WIDTH          {256}
set_component_parameter_value DEVICE_FAMILY       "Agilex 5"
set_component_parameter_value DEVICE_DIE_TYPES    {MAIN_SM7}
set_component_parameter_value PLD_FREQ            {350MHz}
set_component_parameter_value PIPELINE_EN         {1}
save_component

# Adding IOPLL
add_component iopll0 ip/pcie_ed/pcie_ed_iopll0.ip altera_iopll iopll0
load_component iopll0
set_component_parameter_value gui_number_of_clocks        2
set_component_parameter_value gui_fix_vco_frequency       1
set_component_parameter_value gui_fixed_vco_frequency     1410
set_component_parameter_value gui_output_clock_frequency0 250
set_component_parameter_value gui_output_clock_frequency1 350
save_component
set_interface_property refclk EXPORT_OF iopll0.refclk

# Adding Avalon on-chip Memory
add_component MEM0 ip/pcie_ed/pcie_ed_MEM0.ip intel_onchip_memory MEM0
load_component MEM0
set_component_parameter_value dataWidth                   {512}
set_component_parameter_value deviceFamily                "Agilex 5"
set_component_parameter_value dualPort                    {false}
set_component_parameter_value tightly_coupled_ecc         {false}
set_component_parameter_value initMemContent              {true}
set_component_parameter_value initializationFileName      {onchip_mem.hex}
set_component_parameter_value memorySize                  {16384}
set_component_parameter_value readDuringWriteMode_Mixed   {DONT_CARE}
set_component_parameter_value resetrequest_enabled        {false}
set_component_parameter_value singleClockOperation        {false}
set_component_parameter_value lvl1OutputRegA              {0}
set_component_parameter_value lvl2OutputRegA              {1}
set_component_parameter_value useNonDefaultInitFile       {false}
set_component_parameter_value writable                    {true}
save_component

# Connecting PIO
add_connection dut.p0_reset_status_n pio0.reset
add_connection dut.coreclkout_hip_toapp pio0.clk
add_connection iopll0.outclk0 pio0.axi_lite_clk
add_connection iopll0.outclk1 pio0.axi_st_clk
add_connection dut.p0_st_rx pio0.rx_pio
add_connection pio0.tx_pio dut.p0_st_tx
add_connection dut.p0_ss_app_st_rx_tuser_vendor pio0.rx_pio_conduit
add_connection dut.p0_app_ss_st_tx_tuser_vendor pio0.tx_pio_conduit
add_connection dut.p0_st_txcrdt pio0.tx_crdt_pio
add_connection dut.p0_st_ctrlshadow pio0.ctrlshadow_pio
add_connection dut.p0_st_cplto pio0.cplto_pio
add_connection pio0.pio_axi_st_areset_n dut.p0_axi_st_areset_n
add_connection pio0.pio_axi_lite_areset_n dut.p0_axi_lite_areset_n
add_connection pio0.pio_subsystem_cold_rst_n dut.p0_subsystem_cold_rst_n
add_connection pio0.pio_subsystem_warm_rst_n dut.p0_subsystem_warm_rst_n
add_connection dut.p0_subsystem_cold_rst_ack_n pio0.pio_subsystem_cold_rst_ack_n
add_connection dut.p0_subsystem_warm_rst_ack_n pio0.pio_subsystem_warm_rst_ack_n
add_connection pio0.pio_subsystem_rst_req dut.p0_subsystem_rst_req
add_connection pio0.pio_initiate_rst_req_rdy dut.p0_initiate_rst_req_rdy
add_connection dut.p0_subsystem_rst_rdy pio0.pio_subsystem_rst_rdy
add_connection dut.p0_initiate_warmrst_req pio0.pio_initiate_warmrst_req
add_connection resetIP.ninit_done pio0.ninit_done

# Connecting IOPLL
add_connection iopll0.outclk0 dut.p0_axi_lite_clk
add_connection iopll0.outclk1 dut.p0_axi_st_clk
add_connection pio0.pio_pll_locked iopll0.locked
add_connection resetIP.ninit_done iopll0.reset
# Connecting MEM
add_connection pio0.pio_master_reset MEM0.reset1
add_connection pio0.pio_master_clk MEM0.clk1
add_connection pio0.pio_master MEM0.s1

save_system /tmp/arc_903661062/alt9802_2313877265033587028.dir/0002_intel_pcie_gts_0_gen/pcie_ed.qsys
load_system /tmp/arc_903661062/alt9802_2313877265033587028.dir/0002_intel_pcie_gts_0_gen/pcie_ed.qsys
save_system /tmp/arc_903661062/alt9802_2313877265033587028.dir/0002_intel_pcie_gts_0_gen/pcie_ed.qsys
