// pcie_ed_syspll.v

// Generated using ACDS version 23.4.1 205

`timescale 1 ps / 1 ps
module pcie_ed_syspll (
		output wire  o_pll_lock,  //  o_pll_lock.o_pll_lock, Lock signal of PLL
		output wire  o_syspll_c0, // o_syspll_c0.clk,        Clock output C0
		input  wire  i_refclk     // refclk_xcvr.clk,        Input refclock port
	);

	pcie_ed_syspll_intel_systemclk_gts_200_eathmmq #(
		.systempll_c0_output_enable_0 ("ENABLE"),
		.systempll_c1_output_enable_0 ("ENABLE"),
		.systempll_c2_output_enable_0 ("ENABLE"),
		.systempll_f_out_c0_hz_0      ("350000000"),
		.systempll_f_out_c1_hz_0      ("350000000"),
		.systempll_f_out_c2_hz_0      ("350000000"),
		.systempll_f_ref_hz_0         ("100000000"),
		.systempll_ethernet_preset_0  ("ETHERNET_UNUSED"),
		.systempll_pcie_preset_0      ("PCIE_FREQ_350"),
		.systempll_primary_use_0      ("PCIE"),
		.silicon_revision             ("10nm6awhra"),
		.device_revision              ("10nm6awhra")
	) intel_systemclk_gts_inst (
		.o_pll_lock     (o_pll_lock),  //  output,  width = 1,  o_pll_lock.o_pll_lock
		.o_syspll_c0    (o_syspll_c0), //  output,  width = 1, o_syspll_c0.clk
		.i_refclk       (i_refclk),    //   input,  width = 1, refclk_xcvr.clk
		.o_syspll_c1    (),            // (terminated),                         
		.o_syspll_c2    (),            // (terminated),                         
		.i_refclk_ready (1'b0)         // (terminated),                         
	);

endmodule
