// resetIP.v

// Generated using ACDS version 23.4.1 205

`timescale 1 ps / 1 ps
module resetIP (
		output wire  ninit_done  // ninit_done.reset
	);

	altera_s10_user_rst_clkgate resetip (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.reset
	);

endmodule
