// system_intel_pcie_pio_gts_0.v

// Generated using ACDS version 23.4.1 205

`timescale 1 ps / 1 ps
module system_intel_pcie_pio_gts_0 (
		input  wire         Clk_i,                        //                   axi_st_clk.clk
		input  wire         outclk_0,                     //                 axi_lite_clk.clk
		input  wire         coreclkout_hip,               //                          clk.clk
		input  wire         Rstn_i,                       //                        reset.reset_n
		output wire         pio_clk,                      //               pio_master_clk.clk
		output wire         pio_rst_n,                    //             pio_master_reset.reset_n
		output wire         pio_axi_st_areset_n,          //          pio_axi_st_areset_n.reset_n
		output wire         pio_axi_lite_areset_n,        //        pio_axi_lite_areset_n.reset_n
		output wire         pio_subsystem_cold_rst_n,     //     pio_subsystem_cold_rst_n.reset_n
		output wire         pio_subsystem_warm_rst_n,     //     pio_subsystem_warm_rst_n.reset_n
		input  wire         ninit_done,                   //                   ninit_done.reset
		input  wire         pio_subsystem_cold_rst_ack_n, // pio_subsystem_cold_rst_ack_n.subsystem_cold_rst_ack_n
		input  wire         pio_subsystem_warm_rst_ack_n, // pio_subsystem_warm_rst_ack_n.subsystem_warm_rst_ack_n
		input  wire         pio_initiate_warmrst_req,     //     pio_initiate_warmrst_req.initiate_warmrst_req
		input  wire         pio_subsystem_rst_rdy,        //        pio_subsystem_rst_rdy.subsystem_rst_rdy
		output wire         pio_subsystem_rst_req,        //        pio_subsystem_rst_req.subsystem_rst_req
		output wire         pio_initiate_rst_req_rdy,     //     pio_initiate_rst_req_rdy.initiate_rst_req_rdy
		input  wire         pio_pll_locked,               //               pio_pll_locked.export
		output wire [63:0]  pio_address_o,                //                   pio_master.address
		output wire         pio_read_o,                   //                             .read
		input  wire [511:0] pio_readdata_i,               //                             .readdata
		input  wire         pio_readdatavalid_i,          //                             .readdatavalid
		output wire         pio_write_o,                  //                             .write
		output wire [511:0] pio_writedata_o,              //                             .writedata
		input  wire         pio_waitrequest_i,            //                             .waitrequest
		output wire [63:0]  pio_byteenable_o,             //                             .byteenable
		input  wire [1:0]   pio_response_i,               //                             .response
		output wire [3:0]   pio_burstcount_o,             //                             .burstcount
		input  wire         pio_rx_tvalid_i,              //                       rx_pio.tvalid
		output wire         pio_rx_tready_o,              //                             .tready
		input  wire [255:0] pio_rx_tdata_i,               //                             .tdata
		input  wire [31:0]  pio_rx_tkeep_i,               //                             .tkeep
		input  wire         pio_rx_tlast_i,               //                             .tlast
		output wire         pio_tx_tvalid_o,              //                       tx_pio.tvalid
		input  wire         pio_tx_tready_i,              //                             .tready
		output wire [255:0] pio_tx_tdata_o,               //                             .tdata
		output wire [31:0]  pio_tx_tkeep_o,               //                             .tkeep
		output wire         pio_tx_tlast_o,               //                             .tlast
		input  wire         pio_txcrdt_tvalid,            //                  tx_crdt_pio.tvalid
		input  wire [18:0]  pio_txcrdt_tdata,             //                             .tdata
		input  wire         pio_ctrlshadow_tvalid_i,      //               ctrlshadow_pio.tvalid
		input  wire [39:0]  pio_ctrlshadow_tdata_i,       //                             .tdata
		input  wire         pio_cplto_tvalid_i,           //                    cplto_pio.tvalid
		input  wire [29:0]  pio_cplto_tdata_i             //                             .tdata
	);

	system_intel_pcie_pio_gts_0_intel_pcie_pio_gts_234_qrm2xsq #(
		.VFNUM_WIDTH   (11),
		.PFNUM_WIDTH   (2),
		.DATA_WIDTH    (256),
		.DEVICE_FAMILY ("Agilex 5"),
		.PIPELINE_EN   (0)
	) intel_pcie_pio_gts_0 (
		.Clk_i                        (Clk_i),                        //   input,    width = 1,                   axi_st_clk.clk
		.outclk_0                     (outclk_0),                     //   input,    width = 1,                 axi_lite_clk.clk
		.coreclkout_hip               (coreclkout_hip),               //   input,    width = 1,                          clk.clk
		.Rstn_i                       (Rstn_i),                       //   input,    width = 1,                        reset.reset_n
		.pio_clk                      (pio_clk),                      //  output,    width = 1,               pio_master_clk.clk
		.pio_rst_n                    (pio_rst_n),                    //  output,    width = 1,             pio_master_reset.reset_n
		.pio_axi_st_areset_n          (pio_axi_st_areset_n),          //  output,    width = 1,          pio_axi_st_areset_n.reset_n
		.pio_axi_lite_areset_n        (pio_axi_lite_areset_n),        //  output,    width = 1,        pio_axi_lite_areset_n.reset_n
		.pio_subsystem_cold_rst_n     (pio_subsystem_cold_rst_n),     //  output,    width = 1,     pio_subsystem_cold_rst_n.reset_n
		.pio_subsystem_warm_rst_n     (pio_subsystem_warm_rst_n),     //  output,    width = 1,     pio_subsystem_warm_rst_n.reset_n
		.ninit_done                   (ninit_done),                   //   input,    width = 1,                   ninit_done.reset
		.pio_subsystem_cold_rst_ack_n (pio_subsystem_cold_rst_ack_n), //   input,    width = 1, pio_subsystem_cold_rst_ack_n.subsystem_cold_rst_ack_n
		.pio_subsystem_warm_rst_ack_n (pio_subsystem_warm_rst_ack_n), //   input,    width = 1, pio_subsystem_warm_rst_ack_n.subsystem_warm_rst_ack_n
		.pio_initiate_warmrst_req     (pio_initiate_warmrst_req),     //   input,    width = 1,     pio_initiate_warmrst_req.initiate_warmrst_req
		.pio_subsystem_rst_rdy        (pio_subsystem_rst_rdy),        //   input,    width = 1,        pio_subsystem_rst_rdy.subsystem_rst_rdy
		.pio_subsystem_rst_req        (pio_subsystem_rst_req),        //  output,    width = 1,        pio_subsystem_rst_req.subsystem_rst_req
		.pio_initiate_rst_req_rdy     (pio_initiate_rst_req_rdy),     //  output,    width = 1,     pio_initiate_rst_req_rdy.initiate_rst_req_rdy
		.pio_pll_locked               (pio_pll_locked),               //   input,    width = 1,               pio_pll_locked.export
		.pio_address_o                (pio_address_o),                //  output,   width = 64,                   pio_master.address
		.pio_read_o                   (pio_read_o),                   //  output,    width = 1,                             .read
		.pio_readdata_i               (pio_readdata_i),               //   input,  width = 512,                             .readdata
		.pio_readdatavalid_i          (pio_readdatavalid_i),          //   input,    width = 1,                             .readdatavalid
		.pio_write_o                  (pio_write_o),                  //  output,    width = 1,                             .write
		.pio_writedata_o              (pio_writedata_o),              //  output,  width = 512,                             .writedata
		.pio_waitrequest_i            (pio_waitrequest_i),            //   input,    width = 1,                             .waitrequest
		.pio_byteenable_o             (pio_byteenable_o),             //  output,   width = 64,                             .byteenable
		.pio_response_i               (pio_response_i),               //   input,    width = 2,                             .response
		.pio_burstcount_o             (pio_burstcount_o),             //  output,    width = 4,                             .burstcount
		.pio_rx_tvalid_i              (pio_rx_tvalid_i),              //   input,    width = 1,                       rx_pio.tvalid
		.pio_rx_tready_o              (pio_rx_tready_o),              //  output,    width = 1,                             .tready
		.pio_rx_tdata_i               (pio_rx_tdata_i),               //   input,  width = 256,                             .tdata
		.pio_rx_tkeep_i               (pio_rx_tkeep_i),               //   input,   width = 32,                             .tkeep
		.pio_rx_tlast_i               (pio_rx_tlast_i),               //   input,    width = 1,                             .tlast
		.pio_tx_tvalid_o              (pio_tx_tvalid_o),              //  output,    width = 1,                       tx_pio.tvalid
		.pio_tx_tready_i              (pio_tx_tready_i),              //   input,    width = 1,                             .tready
		.pio_tx_tdata_o               (pio_tx_tdata_o),               //  output,  width = 256,                             .tdata
		.pio_tx_tkeep_o               (pio_tx_tkeep_o),               //  output,   width = 32,                             .tkeep
		.pio_tx_tlast_o               (pio_tx_tlast_o),               //  output,    width = 1,                             .tlast
		.pio_txcrdt_tvalid            (pio_txcrdt_tvalid),            //   input,    width = 1,                  tx_crdt_pio.tvalid
		.pio_txcrdt_tdata             (pio_txcrdt_tdata),             //   input,   width = 19,                             .tdata
		.pio_ctrlshadow_tvalid_i      (pio_ctrlshadow_tvalid_i),      //   input,    width = 1,               ctrlshadow_pio.tvalid
		.pio_ctrlshadow_tdata_i       (pio_ctrlshadow_tdata_i),       //   input,   width = 40,                             .tdata
		.pio_cplto_tvalid_i           (pio_cplto_tvalid_i),           //   input,    width = 1,                    cplto_pio.tvalid
		.pio_cplto_tdata_i            (pio_cplto_tdata_i),            //   input,   width = 30,                             .tdata
		.pio_rx_tuser_i               (1'b0),                         // (terminated),                                            
		.pio_rx_tuser_vendor_i        (3'b000),                       // (terminated),                                            
		.pio_tx_tuser_o               (),                             // (terminated),                                            
		.pio_tx_tuser_vendor_o        ()                              // (terminated),                                            
	);

endmodule
