// pcie_ed_pio0_intel_pcie_pio_gts_intelclkctrl_234_dwo3zja.v

// Generated using ACDS version 23.4.1 205

`timescale 1 ps / 1 ps
module pcie_ed_pio0_intel_pcie_pio_gts_intelclkctrl_234_dwo3zja (
		input  wire  inclk,       //       inclk.clk
		output wire  clock_div1x, // clock_div1x.clk
		output wire  clock_div2x  // clock_div2x.clk
	);

	pcie_ed_pio0_intelclkctrl_200_f3nubzq intel_pio_clkctrl (
		.inclk       (inclk),       //   input,  width = 1,       inclk.clk
		.clock_div1x (clock_div1x), //  output,  width = 1, clock_div1x.clk
		.clock_div2x (clock_div2x)  //  output,  width = 1, clock_div2x.clk
	);

endmodule
